---
- name: Running User-Group-LDAP sync
  command: "{{cups_papercut_install_location}}/server/bin/linux-x64/server-command perform-user-and-group-sync-advanced TRUE TRUE"
  when: cups_papercut_ldap
  become: yes
  become_user: "{{cups_papercut_acct_usn}}"